### PR TITLE
Enums

### PR DESCRIPTION
**Pull request by epitka**

### CODE REVIEW

**Comment by ckimes89** [comment]
This looks great! Thanks for adding this test.

**Comment by epitka** [comment]
Do you know why I am not showing under contributors?

**Comment by ckimes89** [comment]
I believe it's because the email address that signed the commit is not the same as the email address for your Github profile.

**Comment by epitka** [comment]
Awww, yes, I can see that I set up GitHub with different address. Darn it...

**Comment by ckimes89** [comment]
It might work if you change the email address on your GitHub profile? I'm not sure if they recalculate after that or if it only counts when you push code or submit a PR.

**Pull request merged**
