### PR TITLE
Support of type conditions

### PR DESCRIPTION
**Pull request by MarianPalkus**
Here a is a simple approach to support type conditions as discussed in https://github.com/ckimes89/graphql-net/issues/54.

There are still some pending issues, but i would like to hear your opinion on this approach before proceeding with the implementation.
This might also be very EF specifc, so i would appreciate any hints to generalize for other queryable backends.

The basic steps are:

- Schema types can have `included types` which represent concrete types for interfaces or inheriting classes for classes. 
This can be done by using the method `GraphQLTypeBuilder.IncludeType()`:
   ```csharp
var character = schema.AddType<Character>();
character.AddField(c => c.Id);
character.AddField(c => c.Name);

var human = character.IncludeType<Human>();
human.AddField(h => (h as Human).Height);

var droid = character.IncludeType<Droid>();
droid.AddField(h => (h as Droid).PrimaryFunction);
```
Theses included types are stored in the property `GraphQLType.IncludedTypes`.

- The parser validates selections in fragments against the type condition of the fragment.
- The `DynamicTypeBuilder` extends the `type` by all properties of it's `IncludedTypes`.
- Special handling of the default field `__typename`:
For types with included types, the field is generated as a field selector with a nested conditional-expression for every included type (using `Expression.TypeIs`) and the 'base type' as the default value.

- The filtering of the result fields is not implemented properly yet.

Some further ideas/remarks:

- The method `GraphQLTypeBuilder.IncludeType()` currently returns a `GraphQLTypeBuilder`, i.e. nested include-types are possible. There should be a class `GraphQlIncludeType` and the method should return a specific builder (`GraphQLIncludeTypeBuilder`) with it's own API to disallow nested include-types.
- The schema definition could be generalized to support different queryable backends. The `is-Type`-Expression as well as the `__typename`-selection-expression  could be passed parametrized.
- The fields of the result have be filtered properly.

What do you think of this approach?

### CODE REVIEW

**Comment by ckimes89** [comment]
First off, thanks for this! This looks like great work. It looks very similar to the approach that I was planning to take. Here's a couple of thoughts that I have:

You mention treating included types as different from regular types by giving them a separate builder, but I think that's neither necessary nor desired. For example, I might want to query by Characters with a fragment for Humans and a fragment for Droids, but I might also just want to query solely for Droids (without having to use fragments). If there is a difference between an included type and a real type, then we can't really do that. This leads to another point, that included types should automatically be added to the base schema.

This also implies that we would have to allow multiple levels of inheritance/inclusions, which I think is also desirable since if a database model is using even one level of inheritance, then chances are likely that they're using more. Supporting this means changing how we handle types in `GraphQLSchema.Complete`.

The model I think is best is to make groups of types keyed by their "base" type, as in the least derived type. So, for example, Character would be the key for a group with Character, Droid, and Human. So, the `Complete` method would group the types by traversing the whole tree, and the `CompleteType` method (maybe `CompleteTypeGroup` now) would then generate one dynamic type for the whole group.

I think this grouping model is important, since it supports Union types when we choose to add them. For example, if I wanted a Union type of BiologicalCreature that could be a Human or an Alien, then I would want a group keyed by BiologicalCreature that contains both Human and Alien. Meanwhile, Human would still be in the inheritance tree for Character.

**Comment by ckimes89** [comment]
Oh, I also think that when building the expression we should automatically handle the casting operations for the user. For example, where you have:

```
var human = character.IncludeType<Human>();
human.AddField(h => (h as Human).Height);
```

We would instead just write that without the cast as:

```
var human = character.IncludeType<Human>();
human.AddField(h => h.Height);
```

Then, when we go to generate the expression if we're building the query using a field with a type condition, then we can automatically insert the casting expressions. This makes the API easier to use from a consumer's standpoint, and it opens the door for us to change the casting operation based on the queryable backend.

**Comment by MarianPalkus** [comment]
Thanks for the feedback.

Yeah, it is probably a better idea to not treat the included types different from the regular types.
I'm going to implement the type-groups as you suggested. 👍

**Comment by MarianPalkus** [comment]
I continued to implement this approach as discussed, it seems to work out pretty well.

The '__typename' property is used to select the properties of result objects for selections with type conditions. Therefore, it is added to the query where necessary. I.e. queries without type conditions should not be modified.

The implementation should support multiple level of inheritance. Added some unit tests to test this, however, i will think on special cases which are not considered yet..

It was not necessary to introduce any new model for type-groups. Currently, the type groups are defined by the type hierarchy represented by the `GraphQlTypes` and their `IncludedTypes` and `BaseType`-property.

To support type unions, it might be sufficient to define a special `GraphQlTypes` representing a type union and to not set the `BaseType`-property of the included types..

Any feedback is welcome :)

**Comment by ckimes89** [comment]
I'll take a closer look at this when I get home and have more time, but at an overview it's looking great!

**Comment by ckimes89** [comment]
Alright, I really like the looks of this! If you take all the new unit tests that were added for EF and add them to `InMemoryExecutionTests.cs`, then I think I'll be ready to merge this PR.

**Comment by MarianPalkus** [comment]
Added the missing unit testst for the memory context - i had to adjust the executor again to support it.
(The related method `Executor.GetBinding` becomes more complex, it might be a good idea trying to refactor/simplify it in the near future.)

Again, i appreciate your feedback :)

**Comment by ckimes89** [comment]
One opportunity for improvement is in the `GetBinding` method. Right now, it looks like we're generating an expression that uses `is` to determine if we can safely cast. That's good since it's necessary for in-memory execution, but as you know it's more than is necessary for EntityFramework where you can just cast and call properties without worry.

I think it makes sense to add another property to `ExpressionOptions` that determines whether we do the `is` check in the expression. We can have it be true in the default expression options for in-memory and false for EF. This would also be useful in the future when we add support for more backends, if they happen to have different requirements for queries on a model with inheritance.

That said, right now everything works with our two officially supported backends, so I'm gonna go ahead and merge. Thanks so much for this work! It's a major feature for the library.

**Pull request merged**
