### PR TITLE
added implementation to resolve enum values

### PR DESCRIPTION
**Pull request by epitka**
see issue #19. Implementation for resolving enum values was missing.

### CODE REVIEW

**Comment by ckimes89** [comment]
Good catch - thanks for this!

**Comment by epitka** [comment]
When will nuget package with this fix be available?

**Comment by ckimes89** [comment]
Version 0.3.5 is available on NuGet with this fix.

**Comment by ckimes89** [comment]
@epitka If you have the time, would you mind adding a test for this fix?

**Comment by epitka** [comment]
ok, let me see what I can put together...

**Comment by epitka** [comment]
I created a branch with tests, but when I tried to create pull request I am getting message that I do not have permission to push the changes ?

**Comment by ckimes89** [comment]
Which branch are you trying to push to? It sounds like you might be trying to push to this repo, whereas you should be pushing to your own repo first and then creating a PR. It's either that or you're failing to authenticate with Github when trying to push changes.

**Pull request merged**
